# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBWCb9XWzxmzK8rLuwEWems6S7ENaR1I
"""

import pandas as pd
data=pd.read_excel('/content/Global Superstore Dataset.xlsx')

data.head()

data.isnull().sum()

data=data.drop_duplicates()

data['Order Date'] = pd.to_datetime(data['Order Date'])

data.info()

data.to_csv("Cleaned_Global_Superstore.csv", index=False)